/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libararymanagementsystemnew1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iresh
 */
public class AddCategory extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    PreparedStatement pst1;
    String s;
    
    public AddCategory() {
        initComponents();
        conn = SQLCON.connect();
        jTable1Load();
    }
    
    private void jTable1Load(){
        try
        {
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM book_category";
            pst = conn.prepareStatement(sql);
            ResultSet rs =  st.executeQuery(sql);
           
           while(rs.next())
           {
               String bookCategoryNo = rs.getString("book_categoryno");
               String bookCategory = rs.getString("book_category");
               String catDescription = rs.getString("category_description");
                
                String tableData[] = {bookCategoryNo, bookCategory, catDescription};
               DefaultTableModel tableModel1 = (DefaultTableModel)jTable1.getModel();
               
               tableModel1.addRow(tableData);
               
           }
        }
       
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
           // System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboOne = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bookCat = new javax.swing.JTextField();
        catDes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        bookCatNo = new javax.swing.JTextField();
        comboOne1 = new javax.swing.JComboBox<>();
        btnComboBox = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        comboOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biographies & Memoirs.", "Education & Reference.", "History.", "Literature & Fiction.", "Sci-Fi & Fantasy.", "Science & Math." }));
        comboOne.setToolTipText("");
        comboOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboOneMouseClicked(evt);
            }
        });
        comboOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOneActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Category Name");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Book Description");

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        catDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catDesActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Category No", "Category Name", "Book Description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Book Category No");

        comboOne1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        comboOne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biographies & Memoirs.", "Education & Reference.", "History.", "Literature & Fiction.", "Sci-Fi & Fantasy.", "Science & Math." }));
        comboOne1.setToolTipText("");
        comboOne1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboOne1MouseClicked(evt);
            }
        });
        comboOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOne1ActionPerformed(evt);
            }
        });

        btnComboBox.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnComboBox.setText("Select Category");
        btnComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComboBoxActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Category");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libararymanagementsystemnew1/resources/shutterstock_132613517-300x200.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catDes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookCatNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126)
                        .addComponent(comboOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnComboBox)
                        .addGap(18, 18, 18)
                        .addComponent(bookCat, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bookCatNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComboBox))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bookCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(catDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catDesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String bookCategoryno= bookCatNo.getText();
        String bookName=bookCat.getText();
        String categoryDescription = catDes.getText();
        
        //display a message when adding items(Are you sure to add the book category?)
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to add the book?","Add",JOptionPane.YES_NO_OPTION);
        if(opt==0)
        
        if (bookCategoryno.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (bookName.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (categoryDescription.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
       else
        {
            String sql = "INSERT INTO book_category (book_categoryno,book_category,category_description) VALUES (?,?,?)";
            try 
            {
                pst = conn.prepareStatement(sql);
                pst.setString(1, bookCatNo.getText());
                pst.setString(2, bookCat.getText());
                pst.setString(3, catDes.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Successfully Added!!");
                
                String bookCategoryNo = bookCatNo.getText();
                String bookCategory = bookCat.getText();
                String categorydescription = catDes.getText();
                
                String tableData[] = {bookCategoryNo,bookCategory, categoryDescription};
               DefaultTableModel tableModel1 = (DefaultTableModel)jTable1.getModel();
               
               tableModel1.addRow(tableData);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              
    String bookCategoryno = bookCatNo.getText();
    String bookCategory = bookCat.getText();
    String categoryDescription = catDes.getText();
    
   
    //display a message when deleting items(Are you sure to delete the book?)
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to delete the book?","Delete",JOptionPane.YES_NO_OPTION);
        if(opt==0)        
            
    try
        {
           
          String sql1 = "DELETE FROM `book_category` WHERE book_categoryno='"+bookCategoryno+"'";
          pst1= conn.prepareStatement(sql1);
          pst1.execute();
           /*ResultSet rs =*/ 
          // pst.executeQuery(sql);
           
           String jTabel1Data[] = {bookCategoryno, bookCategory, categoryDescription};
               DefaultTableModel tableModel1 = (DefaultTableModel)jTable1.getModel();
               int column = 0;
               int row = jTable1.getSelectedRow();
               tableModel1.removeRow(row);
          /* while(rs.next())
           {
               
           String bookcategoryno = rs.getString("book_categoryno");
           String bookcategory = rs.getString("book_category");
           String categorydescription = rs.getString("category_description");
            
           
               
               
               
               String value = jTable1.getModel().getValueAt(row, column).toString();
               
               
               
               
               
               
               
        }*/
           JOptionPane.showMessageDialog(null,"succesefully Delete");


        }   catch (Exception e)
        {
         JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       int selectedRowIndex = jTable1.getSelectedRow();
       
       bookCatNo.setText(model.getValueAt(selectedRowIndex, 0).toString());
       bookCat.setText(model.getValueAt(selectedRowIndex, 1).toString());
       catDes.setText(model.getValueAt(selectedRowIndex, 2).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboOneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOneMouseClicked

    private void comboOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOneActionPerformed
        //String itemText = (String)comboOne.getSelectedItem();

        // TODO add your handling code here:
    }//GEN-LAST:event_comboOneActionPerformed

    private void comboOne1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboOne1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOne1MouseClicked

    private void comboOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOne1ActionPerformed
        String itemText = (String)comboOne1.getSelectedItem();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_comboOne1ActionPerformed

    private void btnComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComboBoxActionPerformed
        String itemText = (String)comboOne1.getSelectedItem( );
        bookCat.setText( itemText );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookCat;
    private javax.swing.JTextField bookCatNo;
    private javax.swing.JButton btnComboBox;
    private javax.swing.JTextField catDes;
    private javax.swing.JComboBox<String> comboOne;
    private javax.swing.JComboBox<String> comboOne1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}