/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libararymanagementsystemnew1;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Acer
 */
public class BookRegistrationForm extends javax.swing.JFrame {
    
    
    Connection conn;
    PreparedStatement pst;
    String s;
    /**
     * Creates new form BookRegistrationForm
     */
    public BookRegistrationForm() {
        initComponents();
        conn = SQLCON.connect();
        ImageIcon  icon = new ImageIcon("C:/Users/-e-/Downloads/lbmNew1/src/libararymanagementsystemnew1/resources/Bookhubicon5.png");
        this.setIconImage(icon.getImage());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bookISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bookAuthor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Blabel = new javax.swing.JLabel();
        bookCopies = new javax.swing.JTextField();
        bookRegBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bookRegSub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Hub");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Registration");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libararymanagementsystemnew1/resources/Bookreg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(2, 0, 870, 136);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Book Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 70, 93, 24);

        bookName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameActionPerformed(evt);
            }
        });
        jPanel2.add(bookName);
        bookName.setBounds(310, 60, 230, 37);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Book ISBN");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 120, 87, 24);

        bookISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(bookISBN);
        bookISBN.setBounds(310, 110, 230, 40);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Book Author");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 170, 98, 24);

        bookAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(bookAuthor);
        bookAuthor.setBounds(310, 160, 230, 39);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Image");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 320, 48, 24);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Number of copies ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 270, 145, 24);

        Blabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Blabel);
        Blabel.setBounds(310, 310, 230, 100);

        bookCopies.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(bookCopies);
        bookCopies.setBounds(310, 260, 230, 37);

        bookRegBack.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bookRegBack.setText("Back");
        bookRegBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRegBackActionPerformed(evt);
            }
        });
        jPanel2.add(bookRegBack);
        bookRegBack.setBounds(140, 440, 80, 30);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setText("Browse");
        jButton1.setActionCommand("Brows");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 440, 100, 30);

        bookRegSub.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bookRegSub.setText("Submit");
        bookRegSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRegSubActionPerformed(evt);
            }
        });
        jPanel2.add(bookRegSub);
        bookRegSub.setBounds(490, 440, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 670, 490);

        setSize(new java.awt.Dimension(684, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameActionPerformed

    private void bookRegSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRegSubActionPerformed
        String bookname = bookName.getText();
        String bookisbn = bookISBN.getText();
        String bookauthor = bookAuthor.getText();
        String bookcopies = bookCopies.getText();

        if (bookname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (bookisbn.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (bookauthor.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if(bookcopies.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else
        {
            String sql = "INSERT INTO book_registration (book_name, book_isbn, book_author, no_of_copies, book_image) VALUES (?,?,?,?,?)";
            try
            {
                pst = conn.prepareStatement(sql);
                InputStream is = new FileInputStream(new File(s));
                pst.setString(1, bookName.getText());
                pst.setString(2, bookISBN.getText());
                pst.setString(3, bookAuthor.getText());
                pst.setString(4, bookCopies.getText());
                pst.setBlob(5,is);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Successfully added!!");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
                
            }
            bookName.setText(null);
            bookISBN.setText(null);
            bookAuthor.setText(null);
            bookCopies.setText(null);
        }
    }//GEN-LAST:event_bookRegSubActionPerformed

    private void bookRegBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRegBackActionPerformed
        this.dispose();
        //Mainmenue menu = new Mainmenue();
        //menu.setVisible(true);
    }//GEN-LAST:event_bookRegBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            Blabel.setIcon(ResizeImage(path));
            s = path;
             
                
                    
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No Data");
        }
        }
        public ImageIcon ResizeImage(String imgPath){
            ImageIcon MyImage = new ImageIcon(imgPath);
            Image img = MyImage.getImage();
            Image newImage = img.getScaledInstance(Blabel.getWidth(), Blabel.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(newImage);
            return image;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Blabel;
    private javax.swing.JTextField bookAuthor;
    private javax.swing.JTextField bookCopies;
    private javax.swing.JTextField bookISBN;
    private javax.swing.JTextField bookName;
    private javax.swing.JButton bookRegBack;
    private javax.swing.JButton bookRegSub;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
