/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libararymanagementsystemnew1;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Acer
 */
public class LibraryRegistrationForm extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    String s;

    /**
     * Creates new form LibraryRegistrationForm
     */
    public LibraryRegistrationForm() {
        initComponents();
        ImageIcon  icon = new ImageIcon("C:/Users/-e-/Downloads/lbmNew1/src/libararymanagementsystemnew1/resources/Bookhubicon5.png");
        this.setIconImage(icon.getImage());
        conn = SQLCON.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        liblabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        librarianPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        librarianEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        librarianAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        librarianNIC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        libName = new javax.swing.JTextField();
        librarianRegSubmitBtn = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Hub");
        setLocation(new java.awt.Point(500, 200));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        liblabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(liblabel);
        liblabel.setBounds(290, 340, 270, 140);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Image");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 340, 59, 22);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(110, 290, 87, 22);

        librarianPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(librarianPassword);
        librarianPassword.setBounds(290, 290, 270, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 240, 49, 22);

        librarianEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(librarianEmail);
        librarianEmail.setBounds(290, 240, 270, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Address");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 190, 71, 22);

        librarianAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(librarianAddress);
        librarianAddress.setBounds(290, 190, 270, 30);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Date of Birth");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 140, 115, 22);

        jDateChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(290, 140, 270, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("NIC");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 100, 35, 22);

        librarianNIC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(librarianNIC);
        librarianNIC.setBounds(290, 90, 270, 30);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 50, 53, 22);

        libName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        libName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libNameActionPerformed(evt);
            }
        });
        jPanel2.add(libName);
        libName.setBounds(290, 40, 270, 30);

        librarianRegSubmitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        librarianRegSubmitBtn.setText("Submit");
        librarianRegSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianRegSubmitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(librarianRegSubmitBtn);
        librarianRegSubmitBtn.setBounds(560, 510, 95, 31);

        btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel2.add(btnback);
        btnback.setBounds(180, 510, 77, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(360, 510, 99, 31);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 690, 560);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Librarian Registration");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(230, 50, 400, 44);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, -1, 810, 0);

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Librarian Registration");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(270, 30, 360, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libararymanagementsystemnew1/resources/librarianreg.png"))); // NOI18N
        jPanel4.add(jLabel10);
        jLabel10.setBounds(120, 10, 110, 110);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 810, 130);

        setSize(new java.awt.Dimension(706, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void libNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libNameActionPerformed

    private void librarianRegSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianRegSubmitBtnActionPerformed
        String libname = libName.getText();
        String librariannic = librarianNIC.getText();
        String librariandob = jDateChooser1.getDateFormatString();
        String librarianaddress = librarianAddress.getText();
        String librarianemail = librarianEmail.getText();
        String librarianpassword = librarianPassword.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-DD");
        
        
        EmailValidator emailValidator = new EmailValidator();
        
        IdentyCardValidator identiyCardValidator = new IdentyCardValidator();
        
        //Sending Email creating the message body
            final String FromEmail = "bookhubworld69@gmail.com";
            final String FromEmailPassword = "cb007874";
            String Subjects = "Book Hub Library Management System";
           
           
           
            Properties properties = new Properties();
           
            properties.put("mail.smtp.starttls.enable","true");
            properties.put("mail.smtp.auth","true");
            properties.put("mail.smtp.host","smtp.gmail.com");
            properties.put("mail.smtp.port","587");
           
            Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator()
            {
                @Override
                protected PasswordAuthentication getPasswordAuthentication()
                {
                    return new PasswordAuthentication(FromEmail,FromEmailPassword);
                }
               
            });
        //_______________________________________
        
        
        if (libname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (!identiyCardValidator.validate(librariannic.trim()))
        {
            JOptionPane.showMessageDialog(null, "Input a valid ID number");
        }
        else if (librariandob.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (librarianaddress.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (!emailValidator.validate(librarianemail.trim()))
        {
            JOptionPane.showMessageDialog(null, "Input Correct Email Format");
        }
        else if(librarianpassword.equals("")){
            JOptionPane.showMessageDialog(null, "Fill Reuired Fields");
        }
        else
        {
            String librarianDOB = sdf.format(jDateChooser1.getDate());
            String sql = "INSERT INTO librarian_registration (lib_name,lib_nic,lib_dob,lib_address,lib_email,lib_password,lib_image) VALUES (?,?,?,?,?,?,?)";
            try 
            {
                pst = conn.prepareStatement(sql);
                InputStream is = new FileInputStream(new File(s));
                pst.setString(1, libName.getText());
                pst.setString(2, librarianNIC.getText());
                pst.setString(3, librarianDOB);
                pst.setString(4, librarianAddress.getText());
                pst.setString(5, librarianEmail.getText());
                pst.setString(6, librarianPassword.getText());
               
                pst.setBlob(7,is);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Seccessfully Added!!");
                
                
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(FromEmail));
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(librarianemail));
                message.setSubject(Subjects);
                //message.setText();
                message.setText( "Dear "+libname+",\n" +
                        "\n" +
                        "Thank you for registering to Bookhub Library as a librarian.\n" +
                        "You registered with this email: " +librarianemail+"\n" +
                        "\n" +
                        "If you have any questions leading up to the event, feel free to reply to this email.\n" +
                        "\n" +
                        "We look forward to see you. \n" +
                        "\n" +
                        "Kind Regards,\n" +
                        "Bookhub Library\n" +
                        "bookhubworld69@gmail.com");
                Transport.send(message);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Apply valid data for the given fields.");
            }
        }
        
        
        libName.setText(null);
        librarianNIC.setText(null);
        //librarianDOB.setText(null);
        librarianAddress.setText(null);
        librarianEmail.setText(null);
        librarianPassword.setText(null);
        jDateChooser1.setDate(null);
        liblabel.setIcon(null);
                                   
    }//GEN-LAST:event_librarianRegSubmitBtnActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        MainMenue1 menu1 = new MainMenue1();
        menu1.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
            liblabel.setIcon(ResizeImage(path));
             s = path;
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
    }                                         
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(liblabel.getWidth(), liblabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    
                   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField libName;
    private javax.swing.JLabel liblabel;
    private javax.swing.JTextField librarianAddress;
    private javax.swing.JTextField librarianEmail;
    private javax.swing.JTextField librarianNIC;
    private javax.swing.JTextField librarianPassword;
    private javax.swing.JButton librarianRegSubmitBtn;
    // End of variables declaration//GEN-END:variables
}
