/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libararymanagementsystemnew1;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class SearchMember extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel d;

    /**
     * Creates new form SearchMember
     */
    public SearchMember() {
        initComponents();
        conn = SQLCON.connect();
        jTable1Load();
    }
    
            private void jTable1Load(){
            int c;
        try {
            pst = conn.prepareStatement("select member_name, nic, address, dob, email, member_id from member_registration;");
            rs = pst.executeQuery();
           
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            d = (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
           
//** While loop for load the data
            while(rs.next())
            {
              Vector v2 = new Vector();
              for(int i=1; i<=c; i++)
              {
              v2.add(rs.getString("member_name"));
              v2.add(rs.getString("nic"));
              v2.add(rs.getString("address"));
              v2.add(rs.getString("dob"));
              v2.add(rs.getString("email"));
              v2.add(String.valueOf(rs.getInt("member_id")));
                                     
              }
             d.addRow(v2);
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(SearchMember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNIC = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jEditDate = new com.toedter.calendar.JDateChooser();
        lblNIC1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNIC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 99, 400, 48));

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 168, 400, 48));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Enter Member DOB");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 207, 48));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Enter Member Address");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 207, 48));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Enter Member Name");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 207, 48));

        lblNIC.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblNIC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNIC.setText("Enter Member NIC");
        jPanel3.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 217, 48));

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel3.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 400, 48));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Enter Member E-mail");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 207, 48));

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 400, 48));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Enter Member ID");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 207, 48));

        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 400, 48));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Name", "Member NIC", "Member Address", "Member DOB", "Member Email", "Member ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 780, -1));

        btnShow.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnShow.setText("Show");
        btnShow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel3.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 162, 51));

        btnEdit.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnEdit.setText("Update");
        btnEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 162, 51));

        btnCancel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, 162, 51));

        btnClear.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 162, 51));
        jPanel3.add(jEditDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 400, 30));

        lblNIC1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNIC1.setText("Enter Member NIC");
        jPanel3.add(lblNIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, -1, -1));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 10, 980, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1480, 710));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1490, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 1498, 757);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
              
        try
        {
            Statement st = conn.createStatement();
            String sql = "select member_name, nic, address, dob, email, member_id from member_registration;"; 
           // pst = conn.prepareStatement(sql); 
            ResultSet rs =  st.executeQuery(sql);
           
           while(rs.next())
           {
               String membername = rs.getString("member_name");
               String membernic = rs.getString("nic");
               String memberaddress = rs.getString("address");
               String memberdob = rs.getString("dob");
               String memberemail = rs.getString("email");
               String memberid = String.valueOf(rs.getInt("member_id"));
               
               
               String tableData[] = {membername, membernic, memberaddress, memberdob, memberemail, memberid};
               DefaultTableModel tableModel1 = (DefaultTableModel)jTable1.getModel();
               
               tableModel1.addRow(tableData);
               
           }
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_btnShowActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        boolean a  = jTable1.isEditing();
        
        if (a==false)
        {
            JOptionPane.showMessageDialog(null, "Click on Edit Button");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        jTable1.setModel(new DefaultTableModel(null, new String[]{"membername", "membernic", "memberaddress", "memberdob", "memberemail", "memberid"}));
        txtAddress.setText(null);
        //txtDOB.setText(null);
        txtEmail.setText(null);
        txtID.setText(null);
        txtNIC.setText(null);
        txtName.setText(null);
        jEditDate.setDate(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String membername = txtName.getText();
        String memberNic = txtNIC.getText();
        String memberaddress = txtAddress.getText();
        //String memberdob = txtDOB.getText();
        String email = txtEmail.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-DD");
        
        
        EmailValidator emailValidator = new EmailValidator();
        
        IdentyCardValidator identiyCardValidator = new IdentyCardValidator();
        
        //Sending Email creating the message body
            final String FromEmail = "bookhubworld69@gmail.com";
            final String FromEmailPassword = "cb007874";
            String Subjects = "Book Hub Library Management System";
           
           
           
            Properties properties = new Properties();
           
            properties.put("mail.smtp.starttls.enable","true");
            properties.put("mail.smtp.auth","true");
            properties.put("mail.smtp.host","smtp.gmail.com");
            properties.put("mail.smtp.port","587");
           
            Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator()
            {
                @Override
                protected PasswordAuthentication getPasswordAuthentication()
                {
                    return new PasswordAuthentication(FromEmail,FromEmailPassword);
                }
               
            });
        //_______________________________________
        
        
        if (membername.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (memberNic.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if (memberaddress.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else if(email.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fill Required fields");
        }
        else
        {
            try
            {
                String memberDOB = sdf.format(jEditDate.getDate());                
                String sql = "update member_registration set member_name = ?, nic = ?, address = ?, dob = ?, email = ?, member_id = ? where nic = '"+memberNic+"'";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtName.getText());
                pst.setString(2, txtNIC.getText());
                pst.setString(3, txtAddress.getText());
                pst.setString(4, memberDOB);
                pst.setString(5, txtEmail.getText());
                pst.setString(6, txtID.getText().toString());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Successfully updated.");
                
                // JavaMail1.sendMail(email);
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(FromEmail));
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(email));
                message.setSubject(Subjects);
                //message.setText();
                message.setText( "Hi " + membername + "! "+"Your details have been successfully updated.");
                Transport.send(message);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            jTable1Load();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        // String membername = txtName.getText();
        String membernic = txtNIC.getText();
        // String memberaddress = txtAddress.getText();
        // String memberdob = txtDOB.getText();
       // String email = txtEmail.getText();
       if (membernic.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Input Member NIC");
       }
       else 
       {
           try
        {
            Statement st = conn.createStatement();
            String memberNic = txtNIC.getText();
            
            String sql = "select * from member_registration where nic = "+memberNic+"";
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.next() == false)
            {
                JOptionPane.showMessageDialog(null, "Invalid NIC");
            }
            String memberNIC = rs.getString("nic");
            txtNIC.setText(memberNIC);
            String memberName = rs.getString("member_name");
            txtName.setText(memberName);
            String memberAddress = rs.getString("address");
            txtAddress.setText(memberAddress);
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-DD");
            String memberDOB = rs.getString("dob");
            java.util.Date memberdob = sdf.parse(memberDOB);
            jEditDate.setDate((java.util.Date)memberdob);
           // txtDOB.setText(memberDOB);
            String memberEmail = rs.getString("email");
            txtEmail.setText(memberEmail);
            String memberID = rs.getString("member_id").toString();
            txtID.setText(memberID);
            
           // txtNIC.setText(null);
        }
        
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
       }           
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String NIC = txtSearch.getText();
        if (NIC.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Input valid details");
        }
       /* else if(NIC.equals(""))
        {
            try
            {
                Statement st = conn.createStatement();

                // JOptionPane.showMessageDialog(null, NIC);

                String sql = "select * from member_registration where nic ='"+NIC+"'";
                ResultSet rs = st.executeQuery(sql);

                while (rs.next())
                {
                    //JOptionPane.showMessageDialog(null, "Invalid NIC");
                    String nic = rs.getString("nic");
                    txtNIC.setText(nic);
                    String name = rs.getString("member_name");
                    txtName.setText(name);
                    SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-DD");
                    String DOB = rs.getString("dob");
                    java.util.Date dob = sdf.parse(DOB);
                    jEditDate.setDate((java.util.Date)dob);
                    String address = rs.getString("address");
                    txtAddress.setText(address);
                    String email = rs.getString("email");
                    txtEmail.setText(email);
                    String memberID = rs.getString("member_id").toString();
                    txtID.setText(memberID);

                }

            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }*/
        else
        {
            try
            {
                Statement st = conn.createStatement();

                // JOptionPane.showMessageDialog(null, NIC);

                String sql = "select * from member_registration where member_name ='"+NIC+"' or nic ='"+NIC+"'";
                ResultSet rs = st.executeQuery(sql);

                while (rs.next())
                {
                    //JOptionPane.showMessageDialog(null, "Invalid NIC");
                    String nic = rs.getString("nic");
                    txtNIC.setText(nic);
                    String name = rs.getString("member_name");
                    txtName.setText(name);
                    SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-DD");
                    String DOB = rs.getString("dob");
                    java.util.Date dob = sdf.parse(DOB);
                    jEditDate.setDate((java.util.Date)dob);
                    String address = rs.getString("address");
                    txtAddress.setText(address);
                    String email = rs.getString("email");
                    txtEmail.setText(email);
                    String memberID = rs.getString("member_id").toString();
                    txtID.setText(memberID);

                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnShow;
    private com.toedter.calendar.JDateChooser jEditDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblNIC1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
